# Generated by Django 4.1 on 2023-02-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('dec', models.TextField()),
            ],
        ),
    ]
